import { Button } from 'aios-ui-kit/button'
import { CodeBlock } from '../../components/CodeBlock'
import { ComponentPreview } from '../../components/ComponentPreview'
import { Prose } from '../../components/Prose'
import { useT } from '../../i18n'
import { DocList, DocNote, DocSection, DocSubSection, DocTable } from './_shared'

const IMPORTS = `// 推荐：子路径导入 / Recommended: subpath import
import { Button } from 'aios-ui-kit/button'
import { Input } from 'aios-ui-kit/input'

// 也可以：从 barrel 导入 / Also fine: the barrel
import { Button, Input } from 'aios-ui-kit'`

const DATA_SLOT = `/* 给某个上下文里的所有按钮加规则，不必给每个按钮传 className */
.toolbar [data-slot='button'] {
  flex: 1;
}`

const DATA_SLOT_TW = `<div className="[&_[data-slot=button]]:flex-1">
  <Button>Save</Button>
  <Button variant="secondary">Cancel</Button>
</div>`

const MERGE = `// 变体给的是 rounded-button（999px）；调用方写 rounded-none 就能覆盖掉
<Button className="rounded-none">Square</Button>

// cn() = clsx + tailwind-merge，同组工具类后写的赢
cn('px-4', 'px-6') // → 'px-6'`

const ICONS = `import { IconArrowRight } from '@tabler/icons-react'

<Button>
  Continue
  <IconArrowRight data-icon="end" />
</Button>`

const AS_LINK_CODE = `import { buttonVariants } from 'aios-ui-kit/button'

<a href="/docs" className={buttonVariants({ variant: 'secondary', size: 'md' })}>
  Read the docs
</a>`

const PREVIEW_CODE = `<Button variant="primary">Primary</Button>
<Button variant="secondary">Secondary</Button>
<Button variant="ghost">Ghost</Button>`

export default function UsagePage() {
  const { t } = useT()

  return (
    <div className="flex flex-col gap-12">
      <DocSection title={t('导入方式', 'Importing')}>
        <CodeBlock code={IMPORTS} />
        <Prose>
          {t(
            '两种写法都合法，但子路径导入更省体积。`package.json` 的 `exports` 把 `aios-ui-kit/<kebab-name>` 映射到 `es/subpath/<kebab-name>.mjs`，每个文件只重新导出一个组件目录。barrel 会把整个 `src/index.ts` 拉进模块图——打包器的 tree-shaking 通常能收拾干净，但只要链路上有任何一个模块带副作用（比如导入了 CSS），摇树就会失效。子路径把这件事变成结构上的保证，而不是运气。',
            'Both are valid, but subpath imports are smaller. The `exports` map in `package.json` points `aios-ui-kit/<kebab-name>` at `es/subpath/<kebab-name>.mjs`, and each of those files re-exports exactly one component directory. The barrel pulls the whole of `src/index.ts` into your module graph — bundlers usually tree-shake that away, but a single side-effectful module anywhere along the way (one that imports CSS, say) is enough to defeat it. Subpaths make the win structural instead of lucky.',
          )}
        </Prose>
        <Prose>
          {t(
            '子路径名一律是组件名的 kebab-case：`DropdownMenu` → `aios-ui-kit/dropdown-menu`。这些文件由 `npm run sync:subpaths` 生成，所以不会漂。',
            'The subpath is always the kebab-case form of the component name: `DropdownMenu` → `aios-ui-kit/dropdown-menu`. Those files are generated by `npm run sync:subpaths`, so they cannot drift.',
          )}
        </Prose>
      </DocSection>

      <DocSection title={t('统一的 variant 词表', 'The shared variant vocabulary')}>
        <Prose>
          {t(
            '变体名在整个库里是同一套。不是每个组件都实现全部七个，但**实现了的一定叫这个名字、长这个样子**——`variant="soft"` 在 Button、Tag、Input 上意味着同一件事。',
            'Variant names are the same library-wide. Not every component implements all seven, but the ones that do **use these names and look like this** — `variant="soft"` means the same thing on a Button, a Tag, and an Input.',
          )}
        </Prose>
        <DocTable
          head={['variant', t('长什么样', 'How it looks')]}
          rows={[
            [
              '`primary`',
              t(
                '实心反相：`bg-foreground-display` + `text-background`。',
                'Inverted solid: `bg-foreground-display` on `text-background`.',
              ),
            ],
            [
              '`primary-outline`',
              t('描边，hover 时反相填充。', 'Outlined; fills inverted on hover.'),
            ],
            [
              '`secondary`',
              t(
                '`border-border-visible` + 透明底。',
                '`border-border-visible` with a transparent fill.',
              ),
            ],
            [
              '`soft`',
              t(
                '`bg-surface-raised` + `border-border`。',
                '`bg-surface-raised` with `border-border`.',
              ),
            ],
            [
              '`outline`',
              t(
                '`border-border` + 透明底，文字对比更弱。',
                '`border-border`, transparent fill, lower-contrast text.',
              ),
            ],
            [
              '`ghost`',
              t(
                '无边框，只有 hover 才出现 `bg-muted`。',
                'No border; `bg-muted` appears only on hover.',
              ),
            ],
            [
              '`destructive`',
              t(
                '`border-accent` + `text-accent`——全库唯一动用 AIOS 红的变体。',
                '`border-accent` and `text-accent` — the only variant that reaches for the AIOS red.',
              ),
            ],
          ]}
        />
        <Prose>
          {t(
            '输入类控件（Input / Textarea / Select / Autocomplete…）通常只有 `outline`（默认）和 `soft` 两个，因为一个输入框不需要七种强调层级。',
            'Input-like controls (Input / Textarea / Select / Autocomplete, …) usually expose only `outline` (the default) and `soft` — a text field does not need seven levels of emphasis.',
          )}
        </Prose>
      </DocSection>

      <DocSection title={t('尺寸', 'Sizes')}>
        <DocTable
          head={['size', t('高度', 'Height'), t('用在哪', 'Where')]}
          rows={[
            [
              '`sm`',
              '36px (`h-9`)',
              t('工具栏、表格行内、密集布局。', 'Toolbars, table rows, dense layouts.'),
            ],
            [
              '`md`',
              '44px (`h-11`)',
              t(
                '默认值。正好等于 `--touch-target-min`。',
                'The default. Exactly `--touch-target-min`.',
              ),
            ],
            [
              '`lg`',
              '52px (`h-13`)',
              t('主要行动号召、落地页。', 'Primary calls to action, landing pages.'),
            ],
          ]}
        />
        <Prose>
          {t(
            '纯图标控件另有 `icon-sm` / `icon-md` / `icon-lg`，它们是正方形（`size-9` / `size-11` / `size-13`），高度和上面对齐。',
            'Icon-only controls add `icon-sm` / `icon-md` / `icon-lg`. Those are square (`size-9` / `size-11` / `size-13`) at the same heights.',
          )}
        </Prose>
        <ComponentPreview code={PREVIEW_CODE} minHeight={120}>
          <div className="flex flex-wrap items-center gap-3">
            <Button variant="primary">Primary</Button>
            <Button variant="secondary">Secondary</Button>
            <Button variant="ghost">Ghost</Button>
          </div>
        </ComponentPreview>
      </DocSection>

      <DocSection title={t('data-slot 约定', 'The data-slot convention')}>
        <Prose>
          {t(
            '每个组件的根元素都带 `data-slot="<kebab-name>"`，子元素用 `data-slot="<name>-<part>"`（比如 `button-icon`、`card-header`）。这不是给库内部用的实现细节，而是对外承诺的样式抓手。',
            'Every component root carries `data-slot="<kebab-name>"`, and its parts carry `data-slot="<name>-<part>"` (`button-icon`, `card-header`, and so on). This is not an internal implementation detail — it is a documented styling hook.',
          )}
        </Prose>
        <CodeBlock code={DATA_SLOT} filename="CSS" />
        <Prose>
          {t(
            '在 Tailwind 里用任意选择器语法也一样：',
            'The same thing with Tailwind’s arbitrary-selector syntax:',
          )}
        </Prose>
        <CodeBlock code={DATA_SLOT_TW} />
        <Prose>
          {t(
            '测试里也应该断言 `data-slot` 和 `data-*` 状态，而不是断言具体的 Tailwind 类名——类名会随变体调整而变，slot 不会。',
            'Tests should assert on `data-slot` and the `data-*` state attributes rather than on specific Tailwind classes: class names change when a variant is tuned, slots do not.',
          )}
        </Prose>
      </DocSection>

      <DocSection title={t('className 是怎么合并的', 'How className merging works')}>
        <Prose>
          {t(
            '组件内部一律写成 `cn(xxxVariants({ … }), className)`，**你的 className 永远在最后**。`cn()` 是 `clsx` + `tailwind-merge`，后者认识工具类的分组，所以同组的后者会真的替换前者，而不是叠加。',
            'Inside every component the pattern is `cn(xxxVariants({ … }), className)`, with **your className last**. `cn()` is `clsx` plus `tailwind-merge`, and `tailwind-merge` understands utility groups, so a later class in the same group genuinely replaces the earlier one instead of piling on top of it.',
          )}
        </Prose>
        <CodeBlock code={MERGE} />
        <DocNote label={t('注意', 'Note')}>
          {t(
            '`tailwind-merge` 被 `extendTailwindMerge` 扩展过，认得 `theme.css` 里的具名刻度（`text-heading`、`rounded-card`、`p-md`、`font-ndot`…）。没登记过的自定义刻度它会当成未知类名原样保留——不会报错，但也不参与去重。',
            '`tailwind-merge` is configured through `extendTailwindMerge` so it knows the named scales from `theme.css` (`text-heading`, `rounded-card`, `p-md`, `font-ndot`, …). A custom scale it has not been told about is kept verbatim as an unknown class — no error, but no de-duplication either.',
          )}
        </DocNote>
      </DocSection>

      <DocSection title={t('图标', 'Icons')}>
        <Prose>
          {t(
            '没有 `leadingIcon` / `trailingIcon` 这类 props。图标就是 children，用 `data-icon="start"` 或 `data-icon="end"` 标一下位置，组件负责那一侧的间距——用的是逻辑属性（`me-2` / `ms-2`），所以 RTL 下自动换边。',
            'There are no `leadingIcon` / `trailingIcon` props. An icon is just a child; mark it `data-icon="start"` or `data-icon="end"` and the component owns the spacing on that side — with logical properties (`me-2` / `ms-2`), so RTL flips it for free.',
          )}
        </Prose>
        <CodeBlock code={ICONS} />
        <DocList
          items={[
            t(
              '`svg` 尺寸由组件通过 `[&_svg]:size-[1.15em]` 跟着字号走，不用手动设 width/height。',
              'SVG size follows the font size via `[&_svg]:size-[1.15em]` on the component; you do not set width/height yourself.',
            ),
            t(
              '纯图标按钮请用 `size="icon-md"` 并补 `aria-label`——没有可读文本的控件对读屏软件是空的。',
              'For icon-only buttons use `size="icon-md"` and supply an `aria-label`; a control with no text content is empty to a screen reader.',
            ),
          ]}
        />
      </DocSection>

      <DocSection title={t('组合与逃生口', 'Composition and escape hatches')}>
        <DocSubSection
          title={t('把 *Variants 直接用在别的元素上', 'Use *Variants on another element')}
        >
          <Prose>
            {t(
              '每个组件的 `index.ts` 都导出对应的 `xxxVariants`。想让一个 `<a>` 长得像按钮，就把类名贴上去——不要把 `<a>` 塞进 `Button` 渲染，那会把 button 语义硬套到链接上。',
              'Every component’s `index.ts` exports its `xxxVariants`. To make an `<a>` look like a button, apply the classes directly — do not render the `<a>` through `Button`, which would force button semantics onto a link.',
            )}
          </Prose>
          <CodeBlock code={AS_LINK_CODE} />
        </DocSubSection>

        <DocSubSection title={t('render prop', 'The render prop')}>
          <Prose>
            {t(
              '基于 Base UI 的组件都支持 `render`，可以换掉渲染的元素或与别的组件组合（例如换成 react-router 的 `Link`）。未在文档里列出的属性会原样透传给底层 primitive。',
              'Components built on Base UI accept `render`, which swaps the rendered element or composes with another component (a react-router `Link`, for instance). Any prop not documented is forwarded straight to the underlying primitive.',
            )}
          </Prose>
        </DocSubSection>

        <DocSubSection title={t('状态变体', 'State variants')}>
          <Prose>
            {t(
              '`theme.css` 注册了一组自定义变体，对应 Base UI 的 `data-*` 约定：`open:` `closed:` `highlighted:` `selected:` `checked:` `unchecked:` `pressed:` `loading:`。主题用 `dark:` / `light:`，它们匹配 `[data-theme]` 而不是 `prefers-color-scheme`。',
              '`theme.css` registers a set of custom variants mirroring Base UI’s `data-*` conventions: `open:` `closed:` `highlighted:` `selected:` `checked:` `unchecked:` `pressed:` `loading:`. For themes use `dark:` / `light:`, which match `[data-theme]` rather than `prefers-color-scheme`.',
            )}
          </Prose>
        </DocSubSection>
      </DocSection>
    </div>
  )
}
