// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0, demoIndex as dmi0 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/docs/showcase.md?type=frontmatter';
import { frontmatter as fm1, toc as t1, demoIndex as dmi1 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/docs/index.md?type=frontmatter';
import { frontmatter as fm2, toc as t2, demoIndex as dmi2 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Accordion/index.md?type=frontmatter';
import { frontmatter as fm3, toc as t3, demoIndex as dmi3 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/AgeMotion/index.md?type=frontmatter';
import { frontmatter as fm4, toc as t4, demoIndex as dmi4 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Alert/index.md?type=frontmatter';
import { frontmatter as fm5, toc as t5, demoIndex as dmi5 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/AspectRatio/index.md?type=frontmatter';
import { frontmatter as fm6, toc as t6, demoIndex as dmi6 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Avatar/index.md?type=frontmatter';
import { frontmatter as fm7, toc as t7, demoIndex as dmi7 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Badge/index.md?type=frontmatter';
import { frontmatter as fm8, toc as t8, demoIndex as dmi8 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Battery/index.md?type=frontmatter';
import { frontmatter as fm9, toc as t9, demoIndex as dmi9 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Breadcrumb/index.md?type=frontmatter';
import { frontmatter as fm10, toc as t10, demoIndex as dmi10 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Button/index.md?type=frontmatter';
import { frontmatter as fm11, toc as t11, demoIndex as dmi11 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Caffeinate/index.md?type=frontmatter';
import { frontmatter as fm12, toc as t12, demoIndex as dmi12 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Calendar/index.md?type=frontmatter';
import { frontmatter as fm13, toc as t13, demoIndex as dmi13 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Card/index.md?type=frontmatter';
import { frontmatter as fm14, toc as t14, demoIndex as dmi14 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Checkbox/index.md?type=frontmatter';
import { frontmatter as fm15, toc as t15, demoIndex as dmi15 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Chrono/index.md?type=frontmatter';
import { frontmatter as fm16, toc as t16, demoIndex as dmi16 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Clipboard/index.md?type=frontmatter';
import { frontmatter as fm17, toc as t17, demoIndex as dmi17 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Collapsible/index.md?type=frontmatter';
import { frontmatter as fm18, toc as t18, demoIndex as dmi18 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Command/index.md?type=frontmatter';
import { frontmatter as fm19, toc as t19, demoIndex as dmi19 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ConfigProvider/index.md?type=frontmatter';
import { frontmatter as fm20, toc as t20, demoIndex as dmi20 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ContextMenu/index.md?type=frontmatter';
import { frontmatter as fm21, toc as t21, demoIndex as dmi21 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DataTable/index.md?type=frontmatter';
import { frontmatter as fm22, toc as t22, demoIndex as dmi22 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Date/index.md?type=frontmatter';
import { frontmatter as fm23, toc as t23, demoIndex as dmi23 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DateNav/index.md?type=frontmatter';
import { frontmatter as fm24, toc as t24, demoIndex as dmi24 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DotMatrix/index.md?type=frontmatter';
import { frontmatter as fm25, toc as t25, demoIndex as dmi25 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DropdownMenu/index.md?type=frontmatter';
import { frontmatter as fm26, toc as t26, demoIndex as dmi26 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ErrorBoundary/index.md?type=frontmatter';
import { frontmatter as fm27, toc as t27, demoIndex as dmi27 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Form/index.md?type=frontmatter';
import { frontmatter as fm28, toc as t28, demoIndex as dmi28 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/HoverCard/index.md?type=frontmatter';
import { frontmatter as fm29, toc as t29, demoIndex as dmi29 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Input/index.md?type=frontmatter';
import { frontmatter as fm30, toc as t30, demoIndex as dmi30 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/InputOTP/index.md?type=frontmatter';
import { frontmatter as fm31, toc as t31, demoIndex as dmi31 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Label/index.md?type=frontmatter';
import { frontmatter as fm32, toc as t32, demoIndex as dmi32 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Modal/index.md?type=frontmatter';
import { frontmatter as fm33, toc as t33, demoIndex as dmi33 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/MotionProvider/index.md?type=frontmatter';
import { frontmatter as fm34, toc as t34, demoIndex as dmi34 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/MusicPlayer/index.md?type=frontmatter';
import { frontmatter as fm35, toc as t35, demoIndex as dmi35 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Navigation/index.md?type=frontmatter';
import { frontmatter as fm36, toc as t36, demoIndex as dmi36 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/NavigationMenu/index.md?type=frontmatter';
import { frontmatter as fm37, toc as t37, demoIndex as dmi37 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/NextEvent/index.md?type=frontmatter';
import { frontmatter as fm38, toc as t38, demoIndex as dmi38 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/OverlayPortal/index.md?type=frontmatter';
import { frontmatter as fm39, toc as t39, demoIndex as dmi39 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Pagination/index.md?type=frontmatter';
import { frontmatter as fm40, toc as t40, demoIndex as dmi40 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/PhotoCarousel/index.md?type=frontmatter';
import { frontmatter as fm41, toc as t41, demoIndex as dmi41 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Pomodoro/index.md?type=frontmatter';
import { frontmatter as fm42, toc as t42, demoIndex as dmi42 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Popover/index.md?type=frontmatter';
import { frontmatter as fm43, toc as t43, demoIndex as dmi43 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ProgressBar/index.md?type=frontmatter';
import { frontmatter as fm44, toc as t44, demoIndex as dmi44 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/QuickToggle/index.md?type=frontmatter';
import { frontmatter as fm45, toc as t45, demoIndex as dmi45 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Quotes/index.md?type=frontmatter';
import { frontmatter as fm46, toc as t46, demoIndex as dmi46 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/RadioGroup/index.md?type=frontmatter';
import { frontmatter as fm47, toc as t47, demoIndex as dmi47 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Resizable/index.md?type=frontmatter';
import { frontmatter as fm48, toc as t48, demoIndex as dmi48 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ScrollArea/index.md?type=frontmatter';
import { frontmatter as fm49, toc as t49, demoIndex as dmi49 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/SegmentedControl/index.md?type=frontmatter';
import { frontmatter as fm50, toc as t50, demoIndex as dmi50 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Select/index.md?type=frontmatter';
import { frontmatter as fm51, toc as t51, demoIndex as dmi51 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Separator/index.md?type=frontmatter';
import { frontmatter as fm52, toc as t52, demoIndex as dmi52 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Sheet/index.md?type=frontmatter';
import { frontmatter as fm53, toc as t53, demoIndex as dmi53 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Sidebar/index.md?type=frontmatter';
import { frontmatter as fm54, toc as t54, demoIndex as dmi54 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Slider/index.md?type=frontmatter';
import { frontmatter as fm55, toc as t55, demoIndex as dmi55 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Spinner/index.md?type=frontmatter';
import { frontmatter as fm56, toc as t56, demoIndex as dmi56 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/States/index.md?type=frontmatter';
import { frontmatter as fm57, toc as t57, demoIndex as dmi57 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/SunDial/index.md?type=frontmatter';
import { frontmatter as fm58, toc as t58, demoIndex as dmi58 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Switch/index.md?type=frontmatter';
import { frontmatter as fm59, toc as t59, demoIndex as dmi59 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/SystemMonitor/index.md?type=frontmatter';
import { frontmatter as fm60, toc as t60, demoIndex as dmi60 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Tabs/index.md?type=frontmatter';
import { frontmatter as fm61, toc as t61, demoIndex as dmi61 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Tag/index.md?type=frontmatter';
import { frontmatter as fm62, toc as t62, demoIndex as dmi62 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Taskbar/index.md?type=frontmatter';
import { frontmatter as fm63, toc as t63, demoIndex as dmi63 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Textarea/index.md?type=frontmatter';
import { frontmatter as fm64, toc as t64, demoIndex as dmi64 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ThemeProvider/index.md?type=frontmatter';
import { frontmatter as fm65, toc as t65, demoIndex as dmi65 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Toggle/index.md?type=frontmatter';
import { frontmatter as fm66, toc as t66, demoIndex as dmi66 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Tooltip/index.md?type=frontmatter';
import { frontmatter as fm67, toc as t67, demoIndex as dmi67 } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/WalkieTalkie/index.md?type=frontmatter';

export const filesMeta = {
  'docs/showcase': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/docs/showcase.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/docs/index.md?type=text'),
  },
  'components/Accordion/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__Accordion" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Accordion/index.md?type=text'),
  },
  'components/AgeMotion/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__AgeMotion" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/AgeMotion/index.md?type=text'),
  },
  'components/Alert/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__Alert" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Alert/index.md?type=text'),
  },
  'components/AspectRatio/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__AspectRatio" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/AspectRatio/index.md?type=text'),
  },
  'components/Avatar/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__Avatar" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Avatar/index.md?type=text'),
  },
  'components/Badge/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__Badge" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Badge/index.md?type=text'),
  },
  'components/Battery/index': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__Battery" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Battery/index.md?type=text'),
  },
  'components/Breadcrumb/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__Breadcrumb" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Breadcrumb/index.md?type=text'),
  },
  'components/Button/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__Button" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Button/index.md?type=text'),
  },
  'components/Caffeinate/index': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__Caffeinate" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Caffeinate/index.md?type=text'),
  },
  'components/Calendar/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__Calendar" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Calendar/index.md?type=text'),
  },
  'components/Card/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__Card" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Card/index.md?type=text'),
  },
  'components/Checkbox/index': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__Checkbox" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Checkbox/index.md?type=text'),
  },
  'components/Chrono/index': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__Chrono" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Chrono/index.md?type=text'),
  },
  'components/Clipboard/index': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__Clipboard" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Clipboard/index.md?type=text'),
  },
  'components/Collapsible/index': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__Collapsible" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Collapsible/index.md?type=text'),
  },
  'components/Command/index': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__Command" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Command/index.md?type=text'),
  },
  'components/ConfigProvider/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__ConfigProvider" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ConfigProvider/index.md?type=text'),
  },
  'components/ContextMenu/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__ContextMenu" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ContextMenu/index.md?type=text'),
  },
  'components/DataTable/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__DataTable" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DataTable/index.md?type=text'),
  },
  'components/Date/index': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__Date" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Date/index.md?type=text'),
  },
  'components/DateNav/index': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__DateNav" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DateNav/index.md?type=text'),
  },
  'components/DotMatrix/index': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__DotMatrix" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DotMatrix/index.md?type=text'),
  },
  'components/DropdownMenu/index': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__DropdownMenu" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/DropdownMenu/index.md?type=text'),
  },
  'components/ErrorBoundary/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__ErrorBoundary" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ErrorBoundary/index.md?type=text'),
  },
  'components/Form/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__Form" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Form/index.md?type=text'),
  },
  'components/HoverCard/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__HoverCard" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/HoverCard/index.md?type=text'),
  },
  'components/Input/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__Input" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Input/index.md?type=text'),
  },
  'components/InputOTP/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__InputOTP" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/InputOTP/index.md?type=text'),
  },
  'components/Label/index': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__Label" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Label/index.md?type=text'),
  },
  'components/Modal/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__Modal" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Modal/index.md?type=text'),
  },
  'components/MotionProvider/index': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__MotionProvider" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/MotionProvider/index.md?type=text'),
  },
  'components/MusicPlayer/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__MusicPlayer" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/MusicPlayer/index.md?type=text'),
  },
  'components/Navigation/index': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__Navigation" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Navigation/index.md?type=text'),
  },
  'components/NavigationMenu/index': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__NavigationMenu" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/NavigationMenu/index.md?type=text'),
  },
  'components/NextEvent/index': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__NextEvent" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/NextEvent/index.md?type=text'),
  },
  'components/OverlayPortal/index': {
    frontmatter: fm38,
    toc: t38,
    demoIndex: dmi38,
    textGetter: () => import(/* webpackChunkName: "meta__OverlayPortal" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/OverlayPortal/index.md?type=text'),
  },
  'components/Pagination/index': {
    frontmatter: fm39,
    toc: t39,
    demoIndex: dmi39,
    textGetter: () => import(/* webpackChunkName: "meta__Pagination" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Pagination/index.md?type=text'),
  },
  'components/PhotoCarousel/index': {
    frontmatter: fm40,
    toc: t40,
    demoIndex: dmi40,
    textGetter: () => import(/* webpackChunkName: "meta__PhotoCarousel" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/PhotoCarousel/index.md?type=text'),
  },
  'components/Pomodoro/index': {
    frontmatter: fm41,
    toc: t41,
    demoIndex: dmi41,
    textGetter: () => import(/* webpackChunkName: "meta__Pomodoro" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Pomodoro/index.md?type=text'),
  },
  'components/Popover/index': {
    frontmatter: fm42,
    toc: t42,
    demoIndex: dmi42,
    textGetter: () => import(/* webpackChunkName: "meta__Popover" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Popover/index.md?type=text'),
  },
  'components/ProgressBar/index': {
    frontmatter: fm43,
    toc: t43,
    demoIndex: dmi43,
    textGetter: () => import(/* webpackChunkName: "meta__ProgressBar" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ProgressBar/index.md?type=text'),
  },
  'components/QuickToggle/index': {
    frontmatter: fm44,
    toc: t44,
    demoIndex: dmi44,
    textGetter: () => import(/* webpackChunkName: "meta__QuickToggle" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/QuickToggle/index.md?type=text'),
  },
  'components/Quotes/index': {
    frontmatter: fm45,
    toc: t45,
    demoIndex: dmi45,
    textGetter: () => import(/* webpackChunkName: "meta__Quotes" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Quotes/index.md?type=text'),
  },
  'components/RadioGroup/index': {
    frontmatter: fm46,
    toc: t46,
    demoIndex: dmi46,
    textGetter: () => import(/* webpackChunkName: "meta__RadioGroup" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/RadioGroup/index.md?type=text'),
  },
  'components/Resizable/index': {
    frontmatter: fm47,
    toc: t47,
    demoIndex: dmi47,
    textGetter: () => import(/* webpackChunkName: "meta__Resizable" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Resizable/index.md?type=text'),
  },
  'components/ScrollArea/index': {
    frontmatter: fm48,
    toc: t48,
    demoIndex: dmi48,
    textGetter: () => import(/* webpackChunkName: "meta__ScrollArea" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ScrollArea/index.md?type=text'),
  },
  'components/SegmentedControl/index': {
    frontmatter: fm49,
    toc: t49,
    demoIndex: dmi49,
    textGetter: () => import(/* webpackChunkName: "meta__SegmentedControl" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/SegmentedControl/index.md?type=text'),
  },
  'components/Select/index': {
    frontmatter: fm50,
    toc: t50,
    demoIndex: dmi50,
    textGetter: () => import(/* webpackChunkName: "meta__Select" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Select/index.md?type=text'),
  },
  'components/Separator/index': {
    frontmatter: fm51,
    toc: t51,
    demoIndex: dmi51,
    textGetter: () => import(/* webpackChunkName: "meta__Separator" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Separator/index.md?type=text'),
  },
  'components/Sheet/index': {
    frontmatter: fm52,
    toc: t52,
    demoIndex: dmi52,
    textGetter: () => import(/* webpackChunkName: "meta__Sheet" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Sheet/index.md?type=text'),
  },
  'components/Sidebar/index': {
    frontmatter: fm53,
    toc: t53,
    demoIndex: dmi53,
    textGetter: () => import(/* webpackChunkName: "meta__Sidebar" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Sidebar/index.md?type=text'),
  },
  'components/Slider/index': {
    frontmatter: fm54,
    toc: t54,
    demoIndex: dmi54,
    textGetter: () => import(/* webpackChunkName: "meta__Slider" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Slider/index.md?type=text'),
  },
  'components/Spinner/index': {
    frontmatter: fm55,
    toc: t55,
    demoIndex: dmi55,
    textGetter: () => import(/* webpackChunkName: "meta__Spinner" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Spinner/index.md?type=text'),
  },
  'components/States/index': {
    frontmatter: fm56,
    toc: t56,
    demoIndex: dmi56,
    textGetter: () => import(/* webpackChunkName: "meta__States" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/States/index.md?type=text'),
  },
  'components/SunDial/index': {
    frontmatter: fm57,
    toc: t57,
    demoIndex: dmi57,
    textGetter: () => import(/* webpackChunkName: "meta__SunDial" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/SunDial/index.md?type=text'),
  },
  'components/Switch/index': {
    frontmatter: fm58,
    toc: t58,
    demoIndex: dmi58,
    textGetter: () => import(/* webpackChunkName: "meta__Switch" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Switch/index.md?type=text'),
  },
  'components/SystemMonitor/index': {
    frontmatter: fm59,
    toc: t59,
    demoIndex: dmi59,
    textGetter: () => import(/* webpackChunkName: "meta__SystemMonitor" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/SystemMonitor/index.md?type=text'),
  },
  'components/Tabs/index': {
    frontmatter: fm60,
    toc: t60,
    demoIndex: dmi60,
    textGetter: () => import(/* webpackChunkName: "meta__Tabs" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Tabs/index.md?type=text'),
  },
  'components/Tag/index': {
    frontmatter: fm61,
    toc: t61,
    demoIndex: dmi61,
    textGetter: () => import(/* webpackChunkName: "meta__Tag" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Tag/index.md?type=text'),
  },
  'components/Taskbar/index': {
    frontmatter: fm62,
    toc: t62,
    demoIndex: dmi62,
    textGetter: () => import(/* webpackChunkName: "meta__Taskbar" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Taskbar/index.md?type=text'),
  },
  'components/Textarea/index': {
    frontmatter: fm63,
    toc: t63,
    demoIndex: dmi63,
    textGetter: () => import(/* webpackChunkName: "meta__Textarea" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Textarea/index.md?type=text'),
  },
  'components/ThemeProvider/index': {
    frontmatter: fm64,
    toc: t64,
    demoIndex: dmi64,
    textGetter: () => import(/* webpackChunkName: "meta__ThemeProvider" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/ThemeProvider/index.md?type=text'),
  },
  'components/Toggle/index': {
    frontmatter: fm65,
    toc: t65,
    demoIndex: dmi65,
    textGetter: () => import(/* webpackChunkName: "meta__Toggle" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Toggle/index.md?type=text'),
  },
  'components/Tooltip/index': {
    frontmatter: fm66,
    toc: t66,
    demoIndex: dmi66,
    textGetter: () => import(/* webpackChunkName: "meta__Tooltip" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/Tooltip/index.md?type=text'),
  },
  'components/WalkieTalkie/index': {
    frontmatter: fm67,
    toc: t67,
    demoIndex: dmi67,
    textGetter: () => import(/* webpackChunkName: "meta__WalkieTalkie" */'/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/WalkieTalkie/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
