import type { ScriptHTMLAttributes } from 'react'
import {
  DEFAULT_THEME_ID_STORAGE_KEY,
  DEFAULT_THEME_SNAPSHOT_STORAGE_KEY,
  THEME_TOKEN_CSS_VARIABLES,
} from './themes'

export interface ThemeScriptOptions {
  /**
   * localStorage key，默认 'aios-theme'
   */
  storageKey?: string
  /**
   * 默认主题，默认 'dark'
   */
  defaultTheme?: 'light' | 'dark' | 'system'
  /**
   * 是否启用系统主题，默认 true
   */
  enableSystem?: boolean
  themeIdStorageKey?: string
  themeSnapshotStorageKey?: string
}

/**
 * 生成内联无闪烁主题脚本字符串。
 *
 * 该脚本应在 <head> 中尽早执行，早于 React 水合，
 * 通过读取 localStorage 和 matchMedia 设置 document.documentElement 的 data-theme。
 *
 * @example
 * ```html
 * <script>
 *   // generated by getThemeScript()
 * </script>
 * ```
 */
export function getThemeScript(options: ThemeScriptOptions = {}): string {
  const {
    storageKey = 'aios-theme',
    defaultTheme = 'dark',
    enableSystem = true,
    themeIdStorageKey = DEFAULT_THEME_ID_STORAGE_KEY,
    themeSnapshotStorageKey = DEFAULT_THEME_SNAPSHOT_STORAGE_KEY,
  } = options

  const script = function (
    storageKey: string,
    defaultTheme: string,
    enableSystem: boolean,
    themeIdStorageKey: string,
    themeSnapshotStorageKey: string,
    properties: Record<string, string>,
  ) {
    const el = document.documentElement
    try {
      const stored = localStorage.getItem(storageKey) || defaultTheme
      let theme = stored
      if (enableSystem && stored === 'system') {
        theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
      }
      if (theme === 'light' || theme === 'dark') {
        el.setAttribute('data-theme', theme)
        const themeId = localStorage.getItem(themeIdStorageKey)
        const snapshot = JSON.parse(localStorage.getItem(themeSnapshotStorageKey) || 'null')
        if (themeId) el.setAttribute('data-theme-id', themeId)
        const selected = snapshot?.modes?.[theme] || snapshot?.modes?.[theme === 'light' ? 'dark' : 'light']
        if (selected) {
          for (const [token, value] of Object.entries(selected)) {
            const property = properties[token]
            if (property && typeof value === 'string') el.style.setProperty(property, value)
          }
        }
      }
    } catch (_e) {
      // storage unavailable — leave the default
    }
  }

  return `(${script.toString()})(${JSON.stringify(storageKey)}, ${JSON.stringify(defaultTheme)}, ${enableSystem}, ${JSON.stringify(themeIdStorageKey)}, ${JSON.stringify(themeSnapshotStorageKey)}, ${JSON.stringify(THEME_TOKEN_CSS_VARIABLES)})`
}

export interface ThemeScriptProps extends ThemeScriptOptions {
  nonce?: string
  scriptProps?: ScriptHTMLAttributes<HTMLScriptElement>
}

/**
 * 渲染内联无闪烁主题脚本。
 *
 * 通常在 <head> 中使用；若使用 Vite 等 SPA，也可直接调用 `getThemeScript()` 将字符串写入 index.html。
 */
export function ThemeScript({ nonce, scriptProps, ...options }: ThemeScriptProps) {
  return (
    <script
      {...scriptProps}
      suppressHydrationWarning
      nonce={typeof window === 'undefined' ? nonce : undefined}
      dangerouslySetInnerHTML={{ __html: getThemeScript(options) }}
    />
  )
}
