import { DEFAULT_THEME_ID_STORAGE_KEY, DEFAULT_THEME_SNAPSHOT_STORAGE_KEY, THEME_TOKEN_CSS_VARIABLES } from "./themes.mjs";
import { jsx } from "react/jsx-runtime";
//#region src/ThemeProvider/ThemeScript.tsx
/**
* 生成内联无闪烁主题脚本字符串。
*
* 该脚本应在 <head> 中尽早执行，早于 React 水合，
* 通过读取 localStorage 和 matchMedia 设置 document.documentElement 的 data-theme。
*
* @example
* ```html
* <script>
*   // generated by getThemeScript()
* <\/script>
* ```
*/
function getThemeScript(options = {}) {
	const { storageKey = "aios-theme", defaultTheme = "dark", enableSystem = true, themeIdStorageKey = DEFAULT_THEME_ID_STORAGE_KEY, themeSnapshotStorageKey = DEFAULT_THEME_SNAPSHOT_STORAGE_KEY } = options;
	const script = function(storageKey, defaultTheme, enableSystem, themeIdStorageKey, themeSnapshotStorageKey, properties) {
		const el = document.documentElement;
		try {
			const stored = localStorage.getItem(storageKey) || defaultTheme;
			let theme = stored;
			if (enableSystem && stored === "system") theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
			if (theme === "light" || theme === "dark") {
				el.setAttribute("data-theme", theme);
				const themeId = localStorage.getItem(themeIdStorageKey);
				const snapshot = JSON.parse(localStorage.getItem(themeSnapshotStorageKey) || "null");
				if (themeId) el.setAttribute("data-theme-id", themeId);
				const selected = snapshot?.modes?.[theme] || snapshot?.modes?.[theme === "light" ? "dark" : "light"];
				if (selected) for (const [token, value] of Object.entries(selected)) {
					const property = properties[token];
					if (property && typeof value === "string") el.style.setProperty(property, value);
				}
			}
		} catch (_e) {}
	};
	return `(${script.toString()})(${JSON.stringify(storageKey)}, ${JSON.stringify(defaultTheme)}, ${enableSystem}, ${JSON.stringify(themeIdStorageKey)}, ${JSON.stringify(themeSnapshotStorageKey)}, ${JSON.stringify(THEME_TOKEN_CSS_VARIABLES)})`;
}
/**
* 渲染内联无闪烁主题脚本。
*
* 通常在 <head> 中使用；若使用 Vite 等 SPA，也可直接调用 `getThemeScript()` 将字符串写入 index.html。
*/
function ThemeScript({ nonce, scriptProps, ...options }) {
	return /* @__PURE__ */ jsx("script", {
		...scriptProps,
		suppressHydrationWarning: true,
		nonce: typeof window === "undefined" ? nonce : void 0,
		dangerouslySetInnerHTML: { __html: getThemeScript(options) }
	});
}
//#endregion
export { ThemeScript, getThemeScript };

//# sourceMappingURL=ThemeScript.mjs.map