import MotionProvider, { useMotionComponent } from "./MotionProvider/index.mjs";
import { AIOS_BUILTIN_THEMES, AIOS_DEFAULT_THEME_ID, DEFAULT_THEME_ID_STORAGE_KEY, DEFAULT_THEME_SNAPSHOT_STORAGE_KEY, REQUIRED_THEME_TOKENS, THEME_TOKEN_CSS_VARIABLES, applyThemeTokens, resolveThemeTokens } from "./ThemeProvider/themes.mjs";
import ThemeProvider, { DEFAULT_STORAGE_KEY, useTheme } from "./ThemeProvider/ThemeProvider.mjs";
import { ThemeScript, getThemeScript } from "./ThemeProvider/ThemeScript.mjs";
import { MAX_THEME_FILE_SIZE, parseDtcgTheme, serializeDtcgTheme } from "./ThemeProvider/dtcg.mjs";
import DirectionProvider, { useDirection } from "./DirectionProvider/DirectionProvider.mjs";
import ReducedMotionProvider, { useReducedMotion } from "./ReducedMotionProvider/ReducedMotionProvider.mjs";
import ConfigProvider, { useCdnFn, useConfig } from "./ConfigProvider/index.mjs";
import { cn, dataAttr, mergeSemanticProps } from "./lib/utils.mjs";
import { mergeRefs } from "./lib/refs.mjs";
import { Slot } from "./lib/slot.mjs";
import { isSingleReactElement } from "./lib/polymorphic.mjs";
import { enterTransition, exitFallbackMs, exitTransition, spring } from "./lib/motion.mjs";
import { OVERLAY_ORIGIN_AWARE, OVERLAY_REDUCED_MOTION, overlayContextMotion, overlayDuration, overlayMenuMotion, overlayModalMotion, overlaySheetTiming, overlayTiming, overlayTooltipMotion } from "./lib/overlay-motion.mjs";
import { FONT_WEIGHT_TRANSITION_CSS, fontVariationWeights, fontWeightValues } from "./lib/fontWeight.mjs";
import { accordionContentVariants, accordionHeaderVariants, accordionItemVariants, accordionLeadingIconVariants, accordionPanelVariants, accordionTriggerIconVariants, accordionTriggerTextVariants, accordionTriggerVariants, accordionVariants } from "./Accordion/accordion-variants.mjs";
import Accordion from "./Accordion/Accordion.mjs";
import { ageMotionVariants } from "./AgeMotion/age-motion-variants.mjs";
import AgeMotion from "./AgeMotion/AgeMotion.mjs";
import { alertIconVariants, alertMessageVariants, alertTitleVariants, alertVariants } from "./Alert/alert-variants.mjs";
import Alert from "./Alert/Alert.mjs";
import { alertDialogBackdropVariants, alertDialogBodyVariants, alertDialogDescriptionVariants, alertDialogFooterVariants, alertDialogHeaderVariants, alertDialogPopupVariants, alertDialogTitleVariants, alertDialogViewportVariants } from "./AlertDialog/alert-dialog-variants.mjs";
import { AlertDialog, AlertDialogBody, AlertDialogClose, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "./AlertDialog/AlertDialog.mjs";
import { buttonVariants } from "./Button/button-variants.mjs";
import Button from "./Button/Button.mjs";
import { iconButtonVariants } from "./Button/icon-button-variants.mjs";
import { IconButton } from "./Button/IconButton.mjs";
import { inputClearGhostVariants, inputClearVariants, inputControlVariants, inputFieldVariants, inputHelperVariants, inputIconVariants, inputLabelVariants, inputVariants, resolveInputVariant } from "./Input/input-variants.mjs";
import Input from "./Input/Input.mjs";
import { switchLabelVariants, switchThumbVariants, switchTrackVariants, switchVariants } from "./Switch/switch-variants.mjs";
import Switch from "./Switch/Switch.mjs";
import { checkboxBoxVariants, checkboxCheckVariants, checkboxDashVariants, checkboxIndicatorVariants, checkboxLabelVariants, checkboxVariants } from "./Checkbox/checkbox-variants.mjs";
import Checkbox from "./Checkbox/Checkbox.mjs";
import { checkboxGroupItemVariants, checkboxGroupMergeBgVariants, checkboxGroupVariants } from "./CheckboxGroup/checkbox-group-variants.mjs";
import CheckboxGroup from "./CheckboxGroup/CheckboxGroup.mjs";
import { askUserQuestionsVariants } from "./AskUserQuestions/ask-user-questions-variants.mjs";
import AskUserQuestions from "./AskUserQuestions/AskUserQuestions.mjs";
import { aspectRatioInnerVariants, aspectRatioVariants } from "./AspectRatio/aspect-ratio-variants.mjs";
import AspectRatio from "./AspectRatio/AspectRatio.mjs";
import { autocompleteClearVariants, autocompleteContentVariants, autocompleteControlVariants, autocompleteEmptyVariants, autocompleteErrorVariants, autocompleteIconVariants, autocompleteInputVariants, autocompleteItemVariants, autocompleteLabelVariants, autocompleteListVariants, autocompletePositionerVariants, autocompleteVariants } from "./Autocomplete/autocomplete-variants.mjs";
import Autocomplete, { AutocompleteContent, AutocompleteEmpty, AutocompleteInput, AutocompleteItem, AutocompleteList } from "./Autocomplete/Autocomplete.mjs";
import { avatarFallbackVariants, avatarVariants } from "./Avatar/avatar-variants.mjs";
import Avatar from "./Avatar/Avatar.mjs";
import { avatarGroupOverflowVariants, avatarGroupVariants } from "./Avatar/avatar-group-variants.mjs";
import { AvatarGroup } from "./Avatar/AvatarGroup.mjs";
import { badgeDotVariants, badgeVariants } from "./Badge/badge-variants.mjs";
import Badge from "./Badge/Badge.mjs";
import { batteryDeviceVariants, batteryRingVariants, batteryVariants } from "./Battery/battery-variants.mjs";
import Battery from "./Battery/Battery.mjs";
import { breadcrumbLinkVariants, breadcrumbVariants } from "./Breadcrumb/breadcrumb-variants.mjs";
import Breadcrumb from "./Breadcrumb/Breadcrumb.mjs";
import { buttonGroupVariants } from "./ButtonGroup/button-group-variants.mjs";
import ButtonGroup from "./ButtonGroup/ButtonGroup.mjs";
import { calendarVariants, dayVariants } from "./Calendar/calendar-variants.mjs";
import Calendar from "./Calendar/Calendar.mjs";
import { contentCardVariants } from "./Card/card-variants.mjs";
import Card, { ContentCard } from "./Card/Card.mjs";
import { carouselButtonVariants, carouselControlsVariants, carouselSlideVariants, carouselStatusVariants, carouselVariants, carouselViewportVariants } from "./Carousel/carousel-variants.mjs";
import Carousel from "./Carousel/Carousel.mjs";
import { chipGroupVariants, chipVariants } from "./Chip/chip-variants.mjs";
import { Chip, ChipGroup } from "./Chip/Chip.mjs";
import { chronoVariants } from "./Chrono/chrono-variants.mjs";
import Chrono from "./Chrono/Chrono.mjs";
import { codeBlockVariants } from "./CodeBlock/code-block-variants.mjs";
import { CodeBlock } from "./CodeBlock/CodeBlock.mjs";
import { codeDiffLineVariants, codeDiffVariants } from "./CodeDiff/code-diff-variants.mjs";
import { CodeDiff } from "./CodeDiff/CodeDiff.mjs";
import { collapsibleContentInnerVariants, collapsibleContentVariants, collapsibleTriggerVariants, collapsibleVariants } from "./Collapsible/collapsible-variants.mjs";
import Collapsible from "./Collapsible/Collapsible.mjs";
import { colorPickerCustomLabelVariants, colorPickerHeaderVariants, colorPickerNativeVariants, colorPickerPreviewVariants, colorPickerSwatchVariants, colorPickerSwatchesVariants, colorPickerTitleVariants, colorPickerValueVariants, colorPickerVariants } from "./ColorPicker/color-picker-variants.mjs";
import ColorPicker from "./ColorPicker/ColorPicker.mjs";
import { comboboxClearVariants, comboboxContentVariants, comboboxControlVariants, comboboxEmptyVariants, comboboxErrorVariants, comboboxIconVariants, comboboxInputVariants, comboboxItemIndicatorVariants, comboboxItemVariants, comboboxLabelVariants, comboboxListVariants, comboboxPositionerVariants, comboboxVariants } from "./Combobox/combobox-variants.mjs";
import Combobox, { ComboboxContent, ComboboxEmpty, ComboboxGroup, ComboboxInput, ComboboxItem, ComboboxItemIndicator, ComboboxList } from "./Combobox/Combobox.mjs";
import { commandEmptyVariants, commandGroupHeadingVariants, commandGroupVariants, commandInputVariants, commandItemIconVariants, commandItemLabelVariants, commandItemShortcutVariants, commandItemVariants, commandListVariants, commandVariants } from "./Command/command-variants.mjs";
import Command from "./Command/Command.mjs";
import { useDisclosure } from "./hooks/useDisclosure.mjs";
import { contextMenuContentVariants, contextMenuItemLabelVariants, contextMenuItemShortcutVariants, contextMenuItemVariants, contextMenuSeparatorVariants, contextMenuTriggerVariants, contextMenuVariants } from "./ContextMenu/context-menu-variants.mjs";
import ContextMenu from "./ContextMenu/ContextMenu.mjs";
import { senderVariants } from "./conversation/Sender/sender-variants.mjs";
import Sender from "./conversation/Sender/Sender.mjs";
import { attachmentVariants } from "./conversation/Attachment/attachment-variants.mjs";
import { Attachment, AttachmentList } from "./conversation/Attachment/Attachment.mjs";
import { branchPickerVariants } from "./conversation/BranchPicker/branch-picker-variants.mjs";
import { BranchPicker } from "./conversation/BranchPicker/BranchPicker.mjs";
import { conversationViewportVariants } from "./conversation/ConversationViewport/conversation-viewport-variants.mjs";
import { ConversationContent, ConversationScrollButton, ConversationViewport } from "./conversation/ConversationViewport/ConversationViewport.mjs";
import { messageVariants } from "./conversation/Message/message-variants.mjs";
import { Message, MessageAction, MessageActions, MessageContent, MessageCopyAction } from "./conversation/Message/Message.mjs";
import { keywordTagVariants } from "./conversation/KeywordTag/keyword-tag-variants.mjs";
import { KeywordTag } from "./conversation/KeywordTag/KeywordTag.mjs";
import { responseVariants } from "./conversation/Response/response-variants.mjs";
import { Response } from "./conversation/Response/Response.mjs";
import { sourceVariants, sourcesVariants } from "./conversation/Sources/sources-variants.mjs";
import { Source, Sources } from "./conversation/Sources/Sources.mjs";
import { streamingTextSegmentVariants, streamingTextVariants } from "./conversation/StreamingText/streaming-text-variants.mjs";
import { StreamingText } from "./conversation/StreamingText/StreamingText.mjs";
import { threadListItemVariants, threadListVariants } from "./conversation/ThreadList/thread-list-variants.mjs";
import { ThreadList, ThreadListItem, ThreadListItemAction, ThreadListNew, ThreadListSection } from "./conversation/ThreadList/ThreadList.mjs";
import { bubbleVariants } from "./conversation/Bubble/bubble-variants.mjs";
import Bubble from "./conversation/Bubble/Bubble.mjs";
import BubbleList from "./conversation/Bubble/BubbleList.mjs";
import { thoughtChainItemVariants, thoughtChainVariants } from "./conversation/ThoughtChain/thought-chain-variants.mjs";
import ThoughtChain from "./conversation/ThoughtChain/ThoughtChain.mjs";
import { promptsItemVariants, promptsVariants } from "./conversation/Prompts/prompts-variants.mjs";
import Prompts from "./conversation/Prompts/Prompts.mjs";
import { welcomeVariants } from "./conversation/Welcome/welcome-variants.mjs";
import Welcome from "./conversation/Welcome/Welcome.mjs";
import { conversationsItemVariants, conversationsVariants } from "./conversation/Conversations/conversations-variants.mjs";
import Conversations from "./conversation/Conversations/Conversations.mjs";
import CopyButton from "./CopyButton/CopyButton.mjs";
import { countdownNumberVariants, countdownVariants } from "./Countdown/countdown-variants.mjs";
import Countdown from "./Countdown/Countdown.mjs";
import DataTable, { dataTableVariants } from "./DataTable/DataTable.mjs";
import { dateFieldInputVariants, dateFieldSegmentVariants, dateFieldVariants } from "./DateField/date-field-variants.mjs";
import DateField from "./DateField/DateField.mjs";
import { dateNavArrowVariants, dateNavLabelVariants, dateNavVariants } from "./DateNav/date-nav-variants.mjs";
import DateNav from "./DateNav/DateNav.mjs";
import { popoverContentVariants, popoverPositionerVariants, popoverTriggerVariants } from "./Popover/popover-variants.mjs";
import Popover from "./Popover/Popover.mjs";
import { datePickerVariants } from "./DatePicker/date-picker-variants.mjs";
import DatePicker from "./DatePicker/DatePicker.mjs";
import { dotMatrixRowVariants, dotMatrixVariants, dotVariants } from "./DotMatrix/dot-matrix-variants.mjs";
import StaticDotMatrix from "./components/StaticDotMatrix.mjs";
import { dropdownMenuContentVariants, dropdownMenuItemIconVariants, dropdownMenuItemLabelVariants, dropdownMenuItemShortcutVariants, dropdownMenuItemVariants, dropdownMenuPositionerVariants, dropdownMenuSeparatorVariants, dropdownMenuTriggerVariants, dropdownMenuVariants, menubarDropdownVariants, menubarItemLabelVariants, menubarItemShortcutVariants, menubarItemVariants, menubarSeparatorVariants, menubarTriggerVariants, menubarVariants } from "./DropdownMenu/dropdown-menu-variants.mjs";
import DropdownMenu from "./DropdownMenu/DropdownMenu.mjs";
import { fieldVariants } from "./Field/field-variants.mjs";
import Field, { FieldDescription, FieldError, FieldLabel } from "./Field/Field.mjs";
import { fieldsetLegendVariants, fieldsetVariants } from "./Fieldset/fieldset-variants.mjs";
import Fieldset from "./Fieldset/Fieldset.mjs";
import { formErrorVariants, formGroupVariants, formVariants } from "./Form/form-variants.mjs";
import Form from "./Form/Form.mjs";
import { gradientGlowVariants } from "./GradientGlow/gradient-glow-variants.mjs";
import GradientGlow from "./GradientGlow/GradientGlow.mjs";
import { hoverCardContentVariants, hoverCardPositionerVariants, hoverCardTriggerVariants } from "./HoverCard/hover-card-variants.mjs";
import HoverCard from "./HoverCard/HoverCard.mjs";
import { iconVariants } from "./Icon/icon-variants.mjs";
import { Icon } from "./Icon/Icon.mjs";
import { iconSwapVariants } from "./IconSwap/icon-swap-variants.mjs";
import IconSwap from "./IconSwap/IconSwap.mjs";
import { inputCopyButtonTextVariants, inputCopyButtonVariants, inputCopyControlVariants, inputCopyFieldVariants, inputCopyLabelVariants, inputCopyVariants } from "./InputCopy/input-copy-variants.mjs";
import InputCopy from "./InputCopy/InputCopy.mjs";
import { inputMessageControlVariants, inputMessageCountVariants, inputMessageFieldVariants, inputMessageHintVariants, inputMessageMetaVariants, inputMessageSendIconVariants, inputMessageSendVariants, inputMessageVariants } from "./InputMessage/input-message-variants.mjs";
import InputMessage from "./InputMessage/InputMessage.mjs";
import { inputOTPInputVariants, inputOTPSlotVariants, inputOTPVariants } from "./InputOTP/input-otp-variants.mjs";
import InputOTP from "./InputOTP/InputOTP.mjs";
import { kbdVariants } from "./Kbd/kbd-variants.mjs";
import Kbd from "./Kbd/Kbd.mjs";
import { labelRequiredVariants, labelTextVariants, labelVariants } from "./Label/label-variants.mjs";
import Label from "./Label/Label.mjs";
import { menubarRootVariants } from "./Menubar/menubar-variants.mjs";
import Menubar from "./Menubar/Menubar.mjs";
import { meterMarkerVariants, meterSegmentVariants, meterTrackVariants, meterValueVariants, meterVariants } from "./Meter/meter-variants.mjs";
import Meter from "./Meter/Meter.mjs";
import { modalBackdropVariants, modalBodyVariants, modalCancelVariants, modalCloseVariants, modalConfirmVariants, modalDescriptionVariants, modalFooterVariants, modalHeaderVariants, modalTitleVariants, modalVariants } from "./Modal/modal-variants.mjs";
import Modal from "./Modal/Modal.mjs";
import { navItemVariants, navigationVariants } from "./Navigation/navigation-variants.mjs";
import Navigation from "./Navigation/Navigation.mjs";
import { navigationMenuCaretVariants, navigationMenuItemVariants, navigationMenuLinkVariants, navigationMenuListVariants, navigationMenuSubmenuItemVariants, navigationMenuSubmenuLinkVariants, navigationMenuSubmenuVariants, navigationMenuVariants } from "./NavigationMenu/navigation-menu-variants.mjs";
import NavigationMenu from "./NavigationMenu/NavigationMenu.mjs";
import { nextEventVariants } from "./NextEvent/next-event-variants.mjs";
import NextEvent from "./NextEvent/NextEvent.mjs";
import { notificationBadgeVariants } from "./NotificationBadge/notification-badge-variants.mjs";
import NotificationBadge from "./NotificationBadge/NotificationBadge.mjs";
import { numberFieldErrorVariants, numberFieldGroupVariants, numberFieldInputVariants, numberFieldLabelVariants, numberFieldStepperVariants, numberFieldVariants } from "./NumberField/number-field-variants.mjs";
import NumberField from "./NumberField/NumberField.mjs";
import { numberTickerVariants } from "./NumberTicker/number-ticker-variants.mjs";
import NumberTicker from "./NumberTicker/NumberTicker.mjs";
import { OverlayPortal, useEscapeKey, useFocusTrap, useOverlayClickOutside, useOverlayState, useScrollLock, useTabCycle } from "./OverlayPortal/OverlayPortal.mjs";
import { paginationArrowVariants, paginationButtonVariants, paginationEllipsisVariants, paginationItemVariants, paginationListVariants, paginationVariants } from "./Pagination/pagination-variants.mjs";
import Pagination from "./Pagination/Pagination.mjs";
import { pomodoroVariants } from "./Pomodoro/pomodoro-variants.mjs";
import Pomodoro from "./Pomodoro/Pomodoro.mjs";
import { thumbnailVariants } from "./Thumbnail/thumbnail-variants.mjs";
import Thumbnail from "./Thumbnail/Thumbnail.mjs";
import { previewCardBodyVariants, previewCardFooterVariants, previewCardMediaVariants, previewCardVariants } from "./PreviewCard/preview-card-variants.mjs";
import PreviewCard from "./PreviewCard/PreviewCard.mjs";
import { progressBarVariants, progressIndeterminateVariants, progressSegmentVariants, progressTrackVariants, progressValueVariants } from "./ProgressBar/progress-bar-variants.mjs";
import ProgressBar from "./ProgressBar/ProgressBar.mjs";
import { quickToggleVariants } from "./QuickToggle/quick-toggle-variants.mjs";
import QuickToggle from "./QuickToggle/QuickToggle.mjs";
import { radioIndicatorVariants, radioVariants } from "./Radio/radio-variants.mjs";
import Radio from "./Radio/Radio.mjs";
import { radioGroupCircleVariants, radioGroupDotVariants, radioGroupItemVariants, radioGroupLabelVariants, radioGroupVariants } from "./RadioGroup/radio-group-variants.mjs";
import RadioGroup from "./RadioGroup/RadioGroup.mjs";
import { resizableHandleVariants, resizablePanelVariants, resizableVariants } from "./Resizable/resizable-variants.mjs";
import Resizable from "./Resizable/Resizable.mjs";
import { scrollAreaScrollbarVariants, scrollAreaThumbVariants, scrollAreaVariants, scrollAreaViewportVariants } from "./ScrollArea/scroll-area-variants.mjs";
import ScrollArea from "./ScrollArea/ScrollArea.mjs";
import { segmentVariants, segmentedHoverSliderVariants, segmentedSliderVariants, segmentedVariants } from "./SegmentedControl/segmented-control-variants.mjs";
import SegmentedControl from "./SegmentedControl/SegmentedControl.mjs";
import { selectContentVariants, selectErrorVariants, selectItemIndicatorVariants, selectItemVariants, selectLabelVariants, selectListVariants, selectPlaceholderVariants, selectPositionerVariants, selectSearchInputVariants, selectSearchVariants, selectTriggerIconVariants, selectTriggerVariants, selectValueVariants, selectVariants } from "./Select/select-variants.mjs";
import Select from "./Select/Select.mjs";
import { separatorLabelVariants, separatorLineVariants, separatorVariants } from "./Separator/separator-variants.mjs";
import Separator from "./Separator/Separator.mjs";
import { sheetBackdropVariants, sheetBodyVariants, sheetCloseVariants, sheetDismissVariants, sheetFooterVariants, sheetHandleBarVariants, sheetHandleVariants, sheetHeaderVariants, sheetSectionTitleVariants, sheetSectionVariants, sheetTitleVariants, sheetVariants } from "./Sheet/sheet-variants.mjs";
import Sheet from "./Sheet/Sheet.mjs";
import { sidebarItemVariants, sidebarVariants } from "./Sidebar/sidebar-variants.mjs";
import Sidebar from "./Sidebar/Sidebar.mjs";
import { skeletonDotVariants, skeletonVariants } from "./Skeleton/skeleton-variants.mjs";
import Skeleton from "./Skeleton/Skeleton.mjs";
import { resolveSliderVariant, sliderControlVariants, sliderFillVariants, sliderHeaderVariants, sliderLabelVariants, sliderThumbVariants, sliderTrackVariants, sliderValueVariants, sliderVariants } from "./Slider/slider-variants.mjs";
import Slider from "./Slider/Slider.mjs";
import Sparkline from "./Sparkline/Sparkline.mjs";
import { spinnerPointerVariants, spinnerSectorVariants, spinnerSvgVariants, spinnerTextVariants, spinnerVariants, spinnerWheelVariants } from "./Spinner/spinner-variants.mjs";
import Spinner from "./Spinner/Spinner.mjs";
import { loadingSegmentVariants, stateVariants } from "./States/states-variants.mjs";
import { DisabledState, EmptyState, ErrorState, LoadingState } from "./States/States.mjs";
import { successCheckVariants } from "./SuccessCheck/success-check-variants.mjs";
import SuccessCheck from "./SuccessCheck/SuccessCheck.mjs";
import { sunDialVariants } from "./SunDial/sun-dial-variants.mjs";
import SunDial from "./SunDial/SunDial.mjs";
import { surfaceVariants } from "./Surfaces/surfaces-variants.mjs";
import Surfaces from "./Surfaces/Surfaces.mjs";
import { monitorItemVariants, monitorSegmentVariants, systemMonitorVariants } from "./SystemMonitor/system-monitor-variants.mjs";
import SystemMonitor from "./SystemMonitor/SystemMonitor.mjs";
import { tabTriggerVariants, tabsHoverBackgroundVariants, tabsIndicatorVariants, tabsListVariants, tabsPanelVariants, tabsVariants } from "./Tabs/tabs-variants.mjs";
import Tabs, { TabPanel } from "./Tabs/Tabs.mjs";
import { tagVariants, tagsVariants } from "./Tag/tag-variants.mjs";
import Tag, { Tags } from "./Tag/Tag.mjs";
import { textAnimateVariants } from "./TextAnimate/text-animate-variants.mjs";
import TextAnimate from "./TextAnimate/TextAnimate.mjs";
import { resolveTextareaVariant, textareaFieldVariants, textareaLabelVariants, textareaMessageVariants, textareaVariants } from "./Textarea/textarea-variants.mjs";
import Textarea from "./Textarea/Textarea.mjs";
import { timeFieldInputVariants, timeFieldSegmentVariants, timeFieldVariants } from "./TimeField/time-field-variants.mjs";
import TimeField from "./TimeField/TimeField.mjs";
import { toastLabelVariants, toastVariants } from "./Toast/toast-variants.mjs";
import Toast from "./Toast/Toast.mjs";
import { tocItemVariants, tocVariants } from "./TOC/toc-variants.mjs";
import TOC from "./TOC/TOC.mjs";
import { resolveToggleVariant, toggleGroupVariants, toggleVariants } from "./Toggle/toggle-variants.mjs";
import Toggle, { ToggleGroup } from "./Toggle/Toggle.mjs";
import { toolbarButtonVariants, toolbarGroupVariants, toolbarLinkVariants, toolbarSeparatorVariants, toolbarVariants } from "./Toolbar/toolbar-variants.mjs";
import Toolbar, { ToolbarButton, ToolbarGroup, ToolbarLink, ToolbarSeparator } from "./Toolbar/Toolbar.mjs";
import { tooltipPopupVariants, tooltipPositionerVariants, tooltipTriggerVariants } from "./Tooltip/tooltip-variants.mjs";
import Tooltip from "./Tooltip/Tooltip.mjs";
import AgentOrb, { agentOrbVariants } from "./agent/AgentOrb/AgentOrb.mjs";
import { activityLabelVariants } from "./agent/ActivityLabel/activity-label-variants.mjs";
import { ActivityLabel } from "./agent/ActivityLabel/ActivityLabel.mjs";
import { assistantPanelVariants } from "./agent/AssistantPanel/assistant-panel-variants.mjs";
import { AssistantPanel } from "./agent/AssistantPanel/AssistantPanel.mjs";
import { AssistantModal } from "./agent/AssistantPanel/AssistantModal.mjs";
import { contextBarLabelVariants, contextBarVariants } from "./agent/ContextBar/context-bar-variants.mjs";
import { ContextBar, ContextBarLabel, ContextBarTasks } from "./agent/ContextBar/ContextBar.mjs";
import { subagentVariants } from "./agent/Subagent/subagent-variants.mjs";
import { Subagent, SubagentList } from "./agent/Subagent/Subagent.mjs";
import { terminalVariants } from "./agent/Terminal/terminal-variants.mjs";
import { Terminal, TerminalLine } from "./agent/Terminal/Terminal.mjs";
import ApprovalGate, { approvalGateVariants } from "./agent/ApprovalGate/ApprovalGate.mjs";
import PlanCard, { planCardVariants } from "./agent/PlanCard/PlanCard.mjs";
import ProgressTrace, { progressTraceVariants } from "./agent/ProgressTrace/ProgressTrace.mjs";
import { reasoningGroupVariants, reasoningVariants } from "./agent/Reasoning/reasoning-variants.mjs";
import { Reasoning, ReasoningGroup, ReasoningSubject } from "./agent/Reasoning/Reasoning.mjs";
import { promptBoxActionVariants, promptBoxVariants } from "./agent/PromptBox/prompt-box-variants.mjs";
import { PromptBox, PromptBoxModelSelect } from "./agent/PromptBox/PromptBox.mjs";
import { planStepVariants, planVariants } from "./agent/Plan/plan-variants.mjs";
import { Plan, PlanItem } from "./agent/Plan/Plan.mjs";
import { Confirmation } from "./agent/Confirmation/Confirmation.mjs";
import { webSearchResultVariants, webSearchVariants } from "./agent/WebSearch/web-search-variants.mjs";
import { WebSearch } from "./agent/WebSearch/WebSearch.mjs";
import ThinkingIndicator, { thinkingIndicatorVariants } from "./agent/ThinkingIndicator/ThinkingIndicator.mjs";
import ThinkingSteps, { thinkingStepsVariants } from "./agent/ThinkingSteps/ThinkingSteps.mjs";
import ToolCallRow, { toolCallRowVariants } from "./agent/ToolCallRow/ToolCallRow.mjs";
import { AicssAgentInput, AicssApprovalCard, AicssCodeBlock, AicssComparisonTable, AicssDataTable, AicssFileDiff, AicssImageGeneration, AicssInlineCitations, AicssOrbs, AicssStreamingText, AicssTaskList, AicssTextResponse, AicssThinkingReasoning, AicssThinkingState, AicssWebSearch } from "./agent/AICSS/AICSS.mjs";
import "./styles/tokens.css";
//#region src/index.ts
const VERSION = "1.0.0";
//#endregion
export { AIOS_BUILTIN_THEMES, AIOS_DEFAULT_THEME_ID, Accordion, ActivityLabel, AgeMotion, AgentOrb, AicssAgentInput, AicssApprovalCard, AicssCodeBlock, AicssComparisonTable, AicssDataTable, AicssFileDiff, AicssImageGeneration, AicssInlineCitations, AicssOrbs, AicssStreamingText, AicssTaskList, AicssTextResponse, AicssThinkingReasoning, AicssThinkingState, AicssWebSearch, Alert, AlertDialog, AlertDialogBody, AlertDialogClose, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger, ApprovalGate, AskUserQuestions, AspectRatio, AssistantModal, AssistantPanel, Attachment, AttachmentList, Autocomplete, AutocompleteContent, AutocompleteEmpty, AutocompleteInput, AutocompleteItem, AutocompleteList, Avatar, AvatarGroup, Badge, Battery, BranchPicker, Breadcrumb, Bubble, BubbleList, Button, ButtonGroup, Calendar, Card, Carousel, Checkbox, CheckboxGroup, Chip, ChipGroup, Chrono, CodeBlock, CodeDiff, Collapsible, ColorPicker, Combobox, ComboboxContent, ComboboxEmpty, ComboboxGroup, ComboboxInput, ComboboxItem, ComboboxItemIndicator, ComboboxList, Command, ConfigProvider, Confirmation, ContentCard, ContextBar, ContextBarLabel, ContextBarTasks, ContextMenu, ConversationContent, ConversationScrollButton, ConversationViewport, Conversations, CopyButton, Countdown, DEFAULT_STORAGE_KEY, DEFAULT_THEME_ID_STORAGE_KEY, DEFAULT_THEME_SNAPSHOT_STORAGE_KEY, DataTable, DateField, DateNav, DatePicker, DirectionProvider, DisabledState, StaticDotMatrix as DotMatrix, DropdownMenu, EmptyState, ErrorState, FONT_WEIGHT_TRANSITION_CSS, Field, FieldDescription, FieldError, FieldLabel, Fieldset, Form, GradientGlow, HoverCard, Icon, IconButton, IconSwap, Input, InputCopy, InputMessage, InputOTP, Kbd, KeywordTag, Label, LoadingState, MAX_THEME_FILE_SIZE, Menubar, Message, MessageAction, MessageActions, MessageContent, MessageCopyAction, Meter, Modal, MotionProvider, Navigation, NavigationMenu, NextEvent, NotificationBadge, NumberField, NumberTicker, OVERLAY_ORIGIN_AWARE, OVERLAY_REDUCED_MOTION, OverlayPortal, Pagination, Plan, PlanCard, PlanItem, Pomodoro, Popover, PreviewCard, ProgressBar, ProgressTrace, PromptBox, PromptBoxModelSelect, Prompts, QuickToggle, REQUIRED_THEME_TOKENS, Radio, RadioGroup, Reasoning, ReasoningGroup, ReasoningSubject, ReducedMotionProvider, Resizable, Response, ScrollArea, SegmentedControl, Select, Sender, Separator, Sheet, Sidebar, Skeleton, Slider, Slot, Source, Sources, Sparkline, Spinner, StreamingText, Subagent, SubagentList, SuccessCheck, SunDial, Surfaces, Switch, SystemMonitor, THEME_TOKEN_CSS_VARIABLES, TOC, TabPanel, Tabs, Tag, Tags, Terminal, TerminalLine, TextAnimate, Textarea, ThemeProvider, ThemeScript, ThinkingIndicator, ThinkingSteps, ThoughtChain, ThreadList, ThreadListItem, ThreadListItemAction, ThreadListNew, ThreadListSection, Thumbnail, TimeField, Toast, Toggle, ToggleGroup, ToolCallRow, Toolbar, ToolbarButton, ToolbarGroup, ToolbarLink, ToolbarSeparator, Tooltip, VERSION, WebSearch, Welcome, accordionContentVariants, accordionHeaderVariants, accordionItemVariants, accordionLeadingIconVariants, accordionPanelVariants, accordionTriggerIconVariants, accordionTriggerTextVariants, accordionTriggerVariants, accordionVariants, activityLabelVariants, ageMotionVariants, agentOrbVariants, alertDialogBackdropVariants, alertDialogBodyVariants, alertDialogDescriptionVariants, alertDialogFooterVariants, alertDialogHeaderVariants, alertDialogPopupVariants, alertDialogTitleVariants, alertDialogViewportVariants, alertIconVariants, alertMessageVariants, alertTitleVariants, alertVariants, applyThemeTokens, approvalGateVariants, askUserQuestionsVariants, aspectRatioInnerVariants, aspectRatioVariants, assistantPanelVariants, attachmentVariants, autocompleteClearVariants, autocompleteContentVariants, autocompleteControlVariants, autocompleteEmptyVariants, autocompleteErrorVariants, autocompleteIconVariants, autocompleteInputVariants, autocompleteItemVariants, autocompleteLabelVariants, autocompleteListVariants, autocompletePositionerVariants, autocompleteVariants, avatarFallbackVariants, avatarGroupOverflowVariants, avatarGroupVariants, avatarVariants, badgeDotVariants, badgeVariants, batteryDeviceVariants, batteryRingVariants, batteryVariants, branchPickerVariants, breadcrumbLinkVariants, breadcrumbVariants, bubbleVariants, buttonGroupVariants, buttonVariants, calendarVariants, carouselButtonVariants, carouselControlsVariants, carouselSlideVariants, carouselStatusVariants, carouselVariants, carouselViewportVariants, checkboxBoxVariants, checkboxCheckVariants, checkboxDashVariants, checkboxGroupItemVariants, checkboxGroupMergeBgVariants, checkboxGroupVariants, checkboxIndicatorVariants, checkboxLabelVariants, checkboxVariants, chipGroupVariants, chipVariants, chronoVariants, cn, codeBlockVariants, codeDiffLineVariants, codeDiffVariants, collapsibleContentInnerVariants, collapsibleContentVariants, collapsibleTriggerVariants, collapsibleVariants, colorPickerCustomLabelVariants, colorPickerHeaderVariants, colorPickerNativeVariants, colorPickerPreviewVariants, colorPickerSwatchVariants, colorPickerSwatchesVariants, colorPickerTitleVariants, colorPickerValueVariants, colorPickerVariants, comboboxClearVariants, comboboxContentVariants, comboboxControlVariants, comboboxEmptyVariants, comboboxErrorVariants, comboboxIconVariants, comboboxInputVariants, comboboxItemIndicatorVariants, comboboxItemVariants, comboboxLabelVariants, comboboxListVariants, comboboxPositionerVariants, comboboxVariants, commandEmptyVariants, commandGroupHeadingVariants, commandGroupVariants, commandInputVariants, commandItemIconVariants, commandItemLabelVariants, commandItemShortcutVariants, commandItemVariants, commandListVariants, commandVariants, contentCardVariants, contextBarLabelVariants, contextBarVariants, contextMenuContentVariants, contextMenuItemLabelVariants, contextMenuItemShortcutVariants, contextMenuItemVariants, contextMenuSeparatorVariants, contextMenuTriggerVariants, contextMenuVariants, conversationViewportVariants, conversationsItemVariants, conversationsVariants, countdownNumberVariants, countdownVariants, dataAttr, dataTableVariants, dateFieldInputVariants, dateFieldSegmentVariants, dateFieldVariants, dateNavArrowVariants, dateNavLabelVariants, dateNavVariants, datePickerVariants, dayVariants, dotMatrixRowVariants, dotMatrixVariants, dotVariants, dropdownMenuContentVariants, dropdownMenuItemIconVariants, dropdownMenuItemLabelVariants, dropdownMenuItemShortcutVariants, dropdownMenuItemVariants, dropdownMenuPositionerVariants, dropdownMenuSeparatorVariants, dropdownMenuTriggerVariants, dropdownMenuVariants, enterTransition, exitFallbackMs, exitTransition, fieldVariants, fieldsetLegendVariants, fieldsetVariants, fontVariationWeights, fontWeightValues, formErrorVariants, formGroupVariants, formVariants, getThemeScript, gradientGlowVariants, hoverCardContentVariants, hoverCardPositionerVariants, hoverCardTriggerVariants, iconButtonVariants, iconSwapVariants, iconVariants, inputClearGhostVariants, inputClearVariants, inputControlVariants, inputCopyButtonTextVariants, inputCopyButtonVariants, inputCopyControlVariants, inputCopyFieldVariants, inputCopyLabelVariants, inputCopyVariants, inputFieldVariants, inputHelperVariants, inputIconVariants, inputLabelVariants, inputMessageControlVariants, inputMessageCountVariants, inputMessageFieldVariants, inputMessageHintVariants, inputMessageMetaVariants, inputMessageSendIconVariants, inputMessageSendVariants, inputMessageVariants, inputOTPInputVariants, inputOTPSlotVariants, inputOTPVariants, inputVariants, isSingleReactElement, kbdVariants, keywordTagVariants, labelRequiredVariants, labelTextVariants, labelVariants, loadingSegmentVariants, menubarDropdownVariants, menubarItemLabelVariants, menubarItemShortcutVariants, menubarItemVariants, menubarRootVariants, menubarSeparatorVariants, menubarTriggerVariants, menubarVariants, mergeRefs, mergeSemanticProps, messageVariants, meterMarkerVariants, meterSegmentVariants, meterTrackVariants, meterValueVariants, meterVariants, modalBackdropVariants, modalBodyVariants, modalCancelVariants, modalCloseVariants, modalConfirmVariants, modalDescriptionVariants, modalFooterVariants, modalHeaderVariants, modalTitleVariants, modalVariants, monitorItemVariants, monitorSegmentVariants, navItemVariants, navigationMenuCaretVariants, navigationMenuItemVariants, navigationMenuLinkVariants, navigationMenuListVariants, navigationMenuSubmenuItemVariants, navigationMenuSubmenuLinkVariants, navigationMenuSubmenuVariants, navigationMenuVariants, navigationVariants, nextEventVariants, notificationBadgeVariants, numberFieldErrorVariants, numberFieldGroupVariants, numberFieldInputVariants, numberFieldLabelVariants, numberFieldStepperVariants, numberFieldVariants, numberTickerVariants, overlayContextMotion, overlayDuration, overlayMenuMotion, overlayModalMotion, overlaySheetTiming, overlayTiming, overlayTooltipMotion, paginationArrowVariants, paginationButtonVariants, paginationEllipsisVariants, paginationItemVariants, paginationListVariants, paginationVariants, parseDtcgTheme, planCardVariants, planStepVariants, planVariants, pomodoroVariants, popoverContentVariants, popoverPositionerVariants, popoverTriggerVariants, previewCardBodyVariants, previewCardFooterVariants, previewCardMediaVariants, previewCardVariants, progressValueVariants as progressBarValueVariants, progressBarVariants, progressIndeterminateVariants, progressSegmentVariants, progressTraceVariants, progressTrackVariants, progressValueVariants, promptBoxActionVariants, promptBoxVariants, promptsItemVariants, promptsVariants, quickToggleVariants, radioGroupCircleVariants, radioGroupDotVariants, radioGroupItemVariants, radioGroupLabelVariants, radioGroupVariants, radioIndicatorVariants, radioVariants, reasoningGroupVariants, reasoningVariants, resizableHandleVariants, resizablePanelVariants, resizableVariants, resolveInputVariant, resolveSliderVariant, resolveTextareaVariant, resolveThemeTokens, resolveToggleVariant, responseVariants, scrollAreaScrollbarVariants, scrollAreaThumbVariants, scrollAreaVariants, scrollAreaViewportVariants, segmentVariants, segmentedHoverSliderVariants, segmentedSliderVariants, segmentedVariants, selectContentVariants, selectErrorVariants, selectItemIndicatorVariants, selectItemVariants, selectLabelVariants, selectListVariants, selectPlaceholderVariants, selectPositionerVariants, selectSearchInputVariants, selectSearchVariants, selectTriggerIconVariants, selectTriggerVariants, selectValueVariants, selectVariants, senderVariants, separatorLabelVariants, separatorLineVariants, separatorVariants, serializeDtcgTheme, sheetBackdropVariants, sheetBodyVariants, sheetCloseVariants, sheetDismissVariants, sheetFooterVariants, sheetHandleBarVariants, sheetHandleVariants, sheetHeaderVariants, sheetSectionTitleVariants, sheetSectionVariants, sheetTitleVariants, sheetVariants, sidebarItemVariants, sidebarVariants, skeletonDotVariants, skeletonVariants, sliderControlVariants, sliderFillVariants, sliderHeaderVariants, sliderLabelVariants, sliderThumbVariants, sliderTrackVariants, sliderValueVariants, sliderVariants, sourceVariants, sourcesVariants, spinnerPointerVariants, spinnerSectorVariants, spinnerSvgVariants, spinnerTextVariants, spinnerVariants, spinnerWheelVariants, spring, stateVariants, streamingTextSegmentVariants, streamingTextVariants, subagentVariants, successCheckVariants, sunDialVariants, surfaceVariants, switchLabelVariants, switchThumbVariants, switchTrackVariants, switchVariants, systemMonitorVariants, tabTriggerVariants, tabsHoverBackgroundVariants, tabsIndicatorVariants, tabsListVariants, tabsPanelVariants, tabsVariants, tagVariants, tagsVariants, terminalVariants, textAnimateVariants, textareaFieldVariants, textareaLabelVariants, textareaMessageVariants, textareaVariants, thinkingIndicatorVariants, thinkingStepsVariants, thoughtChainItemVariants, thoughtChainVariants, threadListItemVariants, threadListVariants, thumbnailVariants, timeFieldInputVariants, timeFieldSegmentVariants, timeFieldVariants, toastLabelVariants, toastVariants, tocItemVariants, tocVariants, toggleGroupVariants, toggleVariants, toolCallRowVariants, toolbarButtonVariants, toolbarGroupVariants, toolbarLinkVariants, toolbarSeparatorVariants, toolbarVariants, tooltipPopupVariants, tooltipPositionerVariants, tooltipTriggerVariants, useCdnFn, useConfig, useDirection, useDisclosure, useEscapeKey, useFocusTrap, useMotionComponent, useOverlayClickOutside, useOverlayState, useReducedMotion, useScrollLock, useTabCycle, useTheme, webSearchResultVariants, webSearchVariants, welcomeVariants };

//# sourceMappingURL=index.mjs.map