import { ComponentConfig, SemanticClassNames, SemanticStyles, WithSemanticProps } from "./lib/types.mjs";
import { cn, dataAttr, mergeSemanticProps } from "./lib/utils.mjs";
import { mergeRefs } from "./lib/refs.mjs";
import { Slot, SlotProps } from "./lib/slot.mjs";
import { AsChildProps, AsProp, PolymorphicProps, isSingleReactElement } from "./lib/polymorphic.mjs";
import { AnchorProps, ButtonPropsBase, ContainerProps, DivProps, InputPropsBase, SelectPropsBase, SpanProps, TextareaPropsBase } from "./lib/component-types.mjs";
import { SpringToken, enterTransition, exitFallbackMs, exitTransition, spring } from "./lib/motion.mjs";
import { OVERLAY_ORIGIN_AWARE, OVERLAY_REDUCED_MOTION, OverlaySpringStep, overlayContextMotion, overlayDuration, overlayMenuMotion, overlayModalMotion, overlaySheetTiming, overlayTiming, overlayTooltipMotion } from "./lib/overlay-motion.mjs";
import { FONT_WEIGHT_TRANSITION_CSS, fontVariationWeights, fontWeightValues } from "./lib/fontWeight.mjs";
export { type AnchorProps, type AsChildProps, type AsProp, type ButtonPropsBase, type ComponentConfig, type ContainerProps, type DivProps, FONT_WEIGHT_TRANSITION_CSS, type InputPropsBase, OVERLAY_ORIGIN_AWARE, OVERLAY_REDUCED_MOTION, type OverlaySpringStep, type PolymorphicProps, type SelectPropsBase, type SemanticClassNames, type SemanticStyles, Slot, type SlotProps, type SpanProps, type SpringToken, type TextareaPropsBase, type WithSemanticProps, cn, dataAttr, enterTransition, exitFallbackMs, exitTransition, fontVariationWeights, fontWeightValues, isSingleReactElement, mergeRefs, mergeSemanticProps, overlayContextMotion, overlayDuration, overlayMenuMotion, overlayModalMotion, overlaySheetTiming, overlayTiming, overlayTooltipMotion, spring };