// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { warning } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/node_modules/rc-util';
import { SiteContext, type ISiteContext } from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/node_modules/dumi/dist/client/theme-api/context.js';
import { components } from '../meta/atoms';
import { locales } from '../locales/config';

import * as entryMemberExports from '/Users/ruishengzhang/Documents/GitHub/Nothing-UI/nothing-design-skill/nothing-design/web-ui-kit/react/src/index.ts';

const entryExports = {
    ...entryMemberExports,
};

// Static content
const pkg = {"name":"nothing-ui-kit-react","description":"Nothing UI Kit Web - A web component library based on Nothing design system","version":"1.0.0","license":"MIT","author":"Nothing UI"};
const historyType = "browser";
const hostname = "";
const themeConfig = {"title":"Nothing UI","footer":"Copyright © 2026 | Powered by <a href=\"https://d.umijs.org\" target=\"_blank\" rel=\"noreferrer\">dumi</a>","prefersColor":{"default":"dark","switch":true},"nprogress":true,"lastUpdated":true,"actions":[{"github":true,"link":"https://github.com/nothing-ui/nothing-ui","openExternal":true,"text":"GitHub"},{"link":"/components/button","text":"Get Started","type":"primary"}],"apiHeader":{"docUrl":"{github}/tree/master/src/{atomId}/index.md","match":["/components"],"pkg":"nothing-ui-kit-react","sourceUrl":"{github}/tree/master/src/{atomId}/index.tsx"},"description":"Nothing UI Kit Web - A web component library based on Nothing design system","name":"Nothing UI","nav":[{"link":"/components/button","title":"Components"},{"link":"/showcase","title":"Showcase"},{"link":"/changelog","title":"Changelog"}],"socialLinks":{"github":"https://github.com/nothing-ui/nothing-ui"}};
const _2_level_nav_available = true;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return (
    <SiteContext.Provider value={context}>
      {outlet}
    </SiteContext.Provider>
  );
}
